name: calib-release

on:
  push:
    branches: [primary]
  workflow_dispatch:

env:
  node_version: 14
  git_email: jpschwartz2@uwalumni.com

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          # fetch full history so things like auto-changelog work properly
          fetch-depth: 0
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ env.node_version }}

      - run: git config --global user.email "${{ env.git_email }}"
      - run: git config --global user.name "${{ github.actor }}"

      # Create a prerelease tag
      - name: Tag
        run: |
          npm version prerelease --preid calibration

      - name: Get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      # push to git
      - name: Push
        run: |
          git push origin v${{ steps.package-version.outputs.current-version}}
          git push origin primary
