name: calib-release

on:
  push:
    branches: [primary]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Git
        run: |
          git config --global user.email "${{ env.git_email }}"
          git config --global user.name "${{ github.actor }}"

      # Create a prerelease tag
      - name: Tag
        run: |
          npm version prerelease --preid calibration

      # push to git
      - name: Push
        run: git push origin primary
