# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: create-release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # fetch full history so things like auto-changelog work properly
          fetch-depth: 0
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ env.node_version }}

      - name: Build
        id: build
        run: |
          npm i
          npm run export

      - name: IPFS
        id: ipfs
        run: npm run store-ipfs
        env:
          WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}

      - name: Test
        run: echo ${{ steps.ipfs.outputs.cid }}

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Visit at: https://${{ steps.ipfs.outputs.cid }}.ipfs.dweb.link
            ${{ steps.Changelog.outputs.changelog }}
